spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db?useSSL=false
    username: user
    password: password
  jpa.hibernate.ddl-auto: update

spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server.port: ${PORT}

aws.s3.endpoint: https://s3-ap-southeast-1.amazonaws.com/