spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false
    username: user
    password: password
  jpa.hibernate.ddl-auto: update

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server.port: 8080
server.url: http://localhost:8080/api/tinyURL