// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU'
export const WINDOW_WIDTH = 'WINDOW-WIDTH'

// Contact Module const
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const HIDE_MESSAGE = 'HIDE_MESSAGE'
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER'
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER'

// Auth const
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER'
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS'
export const SIGNIN_USER = 'SIGNIN_USER'
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR'
export const SIGNOUT_USER = 'SIGNOUT_USER'
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS'
export const INIT_URL = 'INIT_URL'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR'

// Blog const
export const GET_POST_LIST = 'GET_POST_LIST'
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
export const GET_POST = 'GET_POST'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_CATEGORY_LIST = 'GET_POST_CATEGORY_LIST'
export const GET_POST_CATEGORY_LIST_SUCCESS = 'GET_POST_CATEGORY_LIST_SUCCESS'
export const SAVE_OR_UPDATE_POST = 'SAVE_OR_UPDATE_POST'
export const SAVE_OR_UPDATE_POST_SUCCESS = 'SAVE_OR_UPDATE_POST_SUCCESS'

// Todo const
export const GET_ALL_TASK = 'GET_ALL_TASK'
export const GET_ALL_TASK_SUCCESS = 'GET_ALL_TASK_SUCCESS'
export const GET_ALL_TASK_LABEL = 'GET_ALL_TASK_LABEL'
export const GET_ALL_TASK_LABEL_SUCCESS = 'GET_ALL_TASK_LABEL_SUCCESS'
export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE'
export const GET_ALL_TASK_TYPE_SUCCESS = 'GET_ALL_TASK_TYPE_SUCCESS'
export const GET_ALL_TASK_STATUS = 'GET_ALL_TASK_STATUS'
export const GET_ALL_TASK_STATUS_SUCCESS = 'GET_ALL_TASK_STATUS_SUCCESS'
export const SAVE_OR_UPDATE_TASK = 'SAVE_OR_UPDATE_TASK'
export const SAVE_OR_UPDATE_TASK_SUCCESS = 'SAVE_OR_UPDATE_TASK_SUCCESS'
export const SAVE_OR_UPDATE_TASK_ERROR = 'SAVE_OR_UPDATE_TASK_ERROR'

// AWS const
export const GET_S3_FILE_LIST = 'GET_S3_FILE'
export const GET_S3_FILE_LIST_SUCCESS = 'GET_S3_FILE_LIST_SUCCESS'
export const DELETE_S3_FILE = 'DELETE_S3_FILE'
export const DELETE_S3_FILE_SUCCESS = 'DELETE_S3_FILE_SUCCESS'

// TinyURL const
export const GET_TINY_URL = 'GET_TINY_URL'
export const GET_TINY_URL_SUCCESS = 'GET_TINY_URL_SUCCESS'
